// Generated by CoffeeScript 1.3.3
(function() {

  $(document).ready(function() {
    $("#palavra").focus();
    $('#botao').click(function() {
      return $.get('http://www.priberam.pt/SimpleDLPO/VistaGadgetDLPO.aspx', {
        'pal': escape($('#palavra').val())
      }, function(data) {
        var div, table;
        table = $('table', data);
        table = table[3];
        div = $('div', table);
        $('hr', div).remove();
        $('#resultado').empty();
        $('#resultado').css('height', 'auto');
        $('#resultado').append(div);
        $('#resultado div:first').remove();
        $('#resultado div:first').remove();
        $('#resultado div:first').remove();
        return $('#resultado a').attr('target', '_blank');
      });
    });
    $('#palavra').keypress(function(keycode) {
      if (keycode.which === 13) {
        return $('#botao').click();
      }
    });
    $('#load_info').ajaxStart(function() {
      $(this).attr('class', '');
      $('#resultado').slideUp();
      $(this).html('<img src="images/loading.gif" width="50px" height="50px" />');
      $(this).css('display', 'block');
      return $('#palavra').val('');
    });
    $('#load_info').ajaxSuccess(function() {
      $(this).html('');
      $(this).css('display', 'none');
      return $('#resultado').slideDown();
    });
    return $('#load_info').ajaxError(function() {
      $(this).html('');
      $(this).html('Oops! Houve um erro ao recuperar o significado da palavra!');
      return $(this).attr('class', 'error');
    });
  });

}).call(this);
